name = "sql-inventario-elec-fp"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "inventario-departamento"
database_id = "5e996989-1972-481e-a43a-136e25380906"

[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "inventario-documentos"
